### ISSUE TITLE
Missing ? before query string

### ISSUE THREAD

**Issue by Chi-Yu** [rahulmukati/hetzner-dns#1]
Methods `HetznerDNS::getZones()` and `HetznerDNS::getRecords()` are both missing the leading `?` before the query string parameters which essentially means that one cannot pass parameters to these API requests at this point.

**Comment by rahulmukati** [comment]
Fixed!

**Comment by rkaldung** [comment]
Hi @rahulmukati , this fix is not available when using composer

**Comment by rahulmukati** [comment]
> Hi @rahulmukati , this fix is not available when using composer

Hi there,

Updated at composer too, try clearing cache and install again! :)

Cheers!

**Comment by rkaldung** [comment]
> Updated at composer too, try clearing cache and install again! :)

Hi, you probably have to tag a new version.
